import { Component, OnInit } from '@angular/core';
import { SidebarService } from '../../../../../../core/services/utility-services/sidebar.service';
import { SearchArea } from '../../../../../../core/models/config/searcharea';
import { MapService } from '../../../../../../core/services/utility-services/map.service';

@Component({
  selector: 'app-government-structure',
  templateUrl: './government-structure.component.html',
  styleUrls: ['./government-structure.component.scss'],
})
/**
 * Component that gives an overview of the local government structure
 * The displayed data is generated by services and persisted in the search area object
 *
 */
export class GovernmentStructureComponent implements OnInit {
  searchArea: SearchArea;

  constructor(
    private sidebarService: SidebarService,
    private mapService: MapService
  ) {
    this.searchArea = new SearchArea([], 0);
    this.mapService.searchArea$.subscribe((searchArea: SearchArea) => {
      this.searchArea = searchArea;
    });
  }

  ngOnInit(): void {}

  public close() {
    this.sidebarService.toggleGovernment();
  }
}
